# frozen_string_literal: true

require_relative './qwack/base'
require_relative './qwack/base_array'
require_relative './qwack/base_enum'
require_relative './qwack/base_hash'
require_relative './qwack/base_type'
require_relative './qwack/errors'
require_relative './qwack/meta'
require_relative './qwack/types/boolean'
require_relative './qwack/types/date'
require_relative './qwack/types/email'
require_relative './qwack/types/float'
require_relative './qwack/types/integer'
require_relative './qwack/types/string'
